#!/bin/bash
#SBATCH -n 8
#SBATCH -N 1
#SBATCH -p sched_any
#SBATCH -t 0-02:00:00
#SBATCH -o calling_%j.o
#SBATCH -e calling_%j.o
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=meganlecs@gmail.com

python /home/meganle/software/Monopogen/src/Monopogen.py germline -r /home/meganle/software/Monopogen/resource/GRCh38.region.lst -o ./ -a /home/meganle/software/Monopogen/apps -t 8 -s all -g /pool001/meganle/hs38.fa -p /home/meganle/software/Monopogen/example/
