#!/bin/bash
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -p sched_any
#SBATCH -t 0-01:00:00
#SBATCH -o index_%j.o
#SBATCH -e index_%j.o
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=meganlecs@gmail.com

samtools index /pool001/meganle/SNU601_scATAC.bam /pool001/meganle/SNU601_scATAC.bam.bai
